spring:
  application:
    name: geo-land-marketplace
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:land_marketplace}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: app
  flyway:
    schemas: app
    default-schema: app

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
